require("config.lazy")
require("config.keymap")
require("config.settings")
require("config.settings_lsp")
require("config.settings_lualine")
require("config.settings_diff")
require("modules.formatter")
require("modules.check_my_dependencies")
require("modules.diff_two_windows")

vim.cmd([[colorscheme moonfly]])
require("dap-go").setup()
require("lualine").setup()
